### ISSUE TITLE
Running in agent mode does not appear to retreive catalog

### ISSUE THREAD

**Issue by electrofelix** [ffrank/puppet-mgmtgraph#16]
Running 'puppet mgmtgraph' doesn't appear to be retrieving the catalog for my environment yet.

Note: still haven't fixed making sure the environment path exists on machines in my vagrant env by default, which kind of shows that puppet module install expects to only install modules on the puppetmaster as opposed to agents, or at least that's what I'm assuming.

Running in a vagrant environment:
```
mkdir -p /etc/puppetlabs/code/environments/vagrant
sudo /opt/puppetlabs/bin/puppet module install ffrank-mgmtgraph
sudo /opt/puppetlabs/bin/puppet mgmtgraph
```

Produces the following output:
```
---
graph: srv-2.ncs.net
comment: generated from puppet catalog for srv-2.ncs.net
resources:
  noop:
  - name: admissible_Stage[main]
  - name: completed_Stage[main]
  - name: admissible_Class[Settings]
  - name: completed_Class[Settings]
  - name: admissible_Class[Main]
  - name: completed_Class[Main]
edges:
- name: Whit[Completed_class[Settings]] -> Whit[Completed_stage[main]]
  from:
    kind: noop
    name: completed_Class[Settings]
  to:
    kind: noop
    name: completed_Stage[main]
- name: Whit[Completed_class[Main]] -> Whit[Completed_stage[main]]
  from:
    kind: noop
    name: completed_Class[Main]
  to:
    kind: noop
    name: completed_Stage[main]
- name: Whit[Admissible_stage[main]] -> Whit[Admissible_class[Settings]]
  from:
    kind: noop
    name: admissible_Stage[main]
  to:
    kind: noop
    name: admissible_Class[Settings]
- name: Whit[Admissible_class[Settings]] -> Whit[Completed_class[Settings]]
  from:
    kind: noop
    name: admissible_Class[Settings]
  to:
    kind: noop
    name: completed_Class[Settings]
- name: Whit[Admissible_stage[main]] -> Whit[Admissible_class[Main]]
  from:
    kind: noop
    name: admissible_Stage[main]
  to:
    kind: noop
    name: admissible_Class[Main]
- name: Whit[Admissible_class[Main]] -> Whit[Completed_class[Main]]
  from:
    kind: noop
    name: admissible_Class[Main]
  to:
    kind: noop
    name: completed_Class[Main]
```

Where as running `sudo /opt/puppetlabs/bin/puppet agent -t` produces the following:
```
Warning: Setting configtimeout is deprecated. 
   (location: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:1163:in `issue_deprecation_warning')
Info: Using configured environment 'vagrant'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Caching catalog for srv-2.ncs.net
Info: Applying configuration version '1552308129'
Notice: Configure srv-2.ncs.net internal interace on eth2
Notice: /Stage[main]/Ncs::Net/Notify[Configure srv-2.ncs.net internal interace on eth2]/message: defined 'message' as 'Configure srv-2.ncs.net internal interace on eth2'
Notice: Configure srv-2.ncs.net external interface on eth1
Notice: /Stage[main]/Ncs::Net/Notify[Configure srv-2.ncs.net external interface on eth1]/message: defined 'message' as 'Configure srv-2.ncs.net external interface on eth1'
Notice: /Stage[main]/Ncs::Ncszing_171_disable_fstrim/Exec[comment_fstrim_from_cron_weekly]/returns: executed successfully
Notice: /Stage[main]/Ncs::Puppet/Exec[trigger download of puppet5-release-xenial.deb]/returns: executed successfully
Notice: Getting image: 192.168.32.1:5000/ncsre/redis:latest
Notice: /Stage[main]/Ncs::Sensu/Ncs::Docker::Run[sensu-redis]/Notify[Getting image: 192.168.32.1:5000/ncsre/redis:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/redis:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/rabbitmq:3.5.7-management
Notice: /Stage[main]/Ncs::Sensu/Ncs::Docker::Run[sensu-rabbitmq]/Notify[Getting image: 192.168.32.1:5000/ncsre/rabbitmq:3.5.7-management]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/rabbitmq:3.5.7-management'
Notice: Getting image: 192.168.32.1:5000/ncsre/sensu-api:latest
Notice: /Stage[main]/Ncs::Sensu/Ncs::Docker::Run[sensu-api]/Notify[Getting image: 192.168.32.1:5000/ncsre/sensu-api:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/sensu-api:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/sensu-server:latest
Notice: /Stage[main]/Ncs::Sensu/Ncs::Docker::Run[sensu-server]/Notify[Getting image: 192.168.32.1:5000/ncsre/sensu-server:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/sensu-server:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/uchiwa:latest
Notice: /Stage[main]/Ncs::Sensu/Ncs::Docker::Run[sensu-uchiwa]/Notify[Getting image: 192.168.32.1:5000/ncsre/uchiwa:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/uchiwa:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/sensu-client:latest
Notice: /Stage[main]/Ncs::Sensu::Services/Ncs::Docker::Run[sensu-client]/Notify[Getting image: 192.168.32.1:5000/ncsre/sensu-client:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/sensu-client:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/cadvisor:latest
Notice: /Stage[main]/Ncs::Cadvisor/Ncs::Docker::Run[cadvisor]/Notify[Getting image: 192.168.32.1:5000/ncsre/cadvisor:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/cadvisor:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/web:latest
Notice: /Stage[main]/Ncs::Nginxweb/Ncs::Docker::Run[web]/Notify[Getting image: 192.168.32.1:5000/ncsre/web:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/web:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/changelogs:latest
Notice: /Stage[main]/Ncs::Changelogs/Ncs::Docker::Run[changelogs]/Notify[Getting image: 192.168.32.1:5000/ncsre/changelogs:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/changelogs:latest'
Notice: /Stage[main]/Ncs::Gerrit/Ncs::Storage[gerrit]/Exec[Check /mnt/gerrit]/returns: executed successfully
Notice: Getting image: 192.168.32.1:5000/ncsre/gerrit:latest
Notice: /Stage[main]/Ncs::Gerrit/Ncs::Docker::Run[gerrit]/Notify[Getting image: 192.168.32.1:5000/ncsre/gerrit:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/gerrit:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/jeepyb:latest
Notice: /Stage[main]/Ncs::Jeepyb/Ncs::Docker::Run[jeepyb]/Notify[Getting image: 192.168.32.1:5000/ncsre/jeepyb:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/jeepyb:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/zuul:latest
Notice: /Stage[main]/Ncs::Zuul::Scheduler/Ncs::Docker::Run[zuul-scheduler]/Notify[Getting image: 192.168.32.1:5000/ncsre/zuul:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/zuul:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/elasticsearch:latest
Notice: /Stage[main]/Ncs::Elasticsearch/Ncs::Docker::Run[elasticsearch]/Notify[Getting image: 192.168.32.1:5000/ncsre/elasticsearch:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/elasticsearch:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/gearmanworker:latest
Notice: /Stage[main]/Ncs::Gearmanworker/Ncs::Docker::Run[gearmanworker]/Notify[Getting image: 192.168.32.1:5000/ncsre/gearmanworker:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/gearmanworker:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/kibana:latest
Notice: /Stage[main]/Ncs::Kibana/Ncs::Docker::Run[kibana]/Notify[Getting image: 192.168.32.1:5000/ncsre/kibana:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/kibana:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/logstash:latest
Notice: /Stage[main]/Ncs::Logstash/Ncs::Docker::Run[logstash]/Notify[Getting image: 192.168.32.1:5000/ncsre/logstash:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/logstash:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/graphite-statsd:latest
Notice: /Stage[main]/Ncs::Graphite_statsd/Ncs::Docker::Run[graphite-statsd]/Notify[Getting image: 192.168.32.1:5000/ncsre/graphite-statsd:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/graphite-statsd:latest'
Notice: Getting image: 192.168.32.1:5000/ncsre/prometheus:latest
Notice: /Stage[main]/Ncs::Prometheus/Ncs::Docker::Run[prometheus]/Notify[Getting image: 192.168.32.1:5000/ncsre/prometheus:latest]/message: defined 'message' as 'Getting image: 192.168.32.1:5000/ncsre/prometheus:latest'
Notice: /Stage[main]/Ncs::Jeepyb/Ncs::Docker::Run[jeepyb]/Docker::Run[jeepyb]/Exec[remove jeepyb container]/returns: executed successfully
Notice: /Stage[main]/Ncs::Jeepyb/Ncs::Docker::Run[jeepyb]/Docker::Run[jeepyb]/Exec[remove jeepyb cidfile]/returns: executed successfully
Info: /Stage[main]/Ncs::Jeepyb/Ncs::Docker::Run[jeepyb]/Docker::Run[jeepyb]/Exec[remove jeepyb cidfile]: Scheduling refresh of Exec[run jeepyb with docker]
Notice: /Stage[main]/Ncs::Jeepyb/Ncs::Docker::Run[jeepyb]/Docker::Run[jeepyb]/Exec[run jeepyb with docker]: Triggered 'refresh' from 1 event
Info: Wait_for[wait for container to exit](provider=wait_for): Query output matched regex.
Notice: Applied catalog in 15.75 seconds
```

Suggests that the catalog wasn't retrieved in the way expected.

Looking at puppets other commands `sudo /opt/puppetlabs/bin/puppet catalog find` returns the following output:
```
Warning: Setting configtimeout is deprecated. 
   (location: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:1163:in `issue_deprecation_warning')
Notice: Compiled catalog for srv-2.ncs.net in environment vagrant in 0.02 seconds
{
  "tags": [
    "settings"
  ],
  "name": "srv-2.ncs.net",
  "version": 1552309089,
  "code_id": null,
  "catalog_uuid": "8c2f17b4-35e8-4163-8756-78a98f26e660",
  "catalog_format": 1,
  "environment": "vagrant",
  "resources": [
    {
      "type": "Stage",
      "title": "main",
      "tags": [
        "stage"
      ],
      "exported": false,
      "parameters": {
        "name": "main"
      }
    },
    {
      "type": "Class",
      "title": "Settings",
      "tags": [
        "class",
        "settings"
      ],
      "exported": false
    },
    {
      "type": "Class",
      "title": "main",
      "tags": [
        "class"
      ],
      "exported": false,
      "parameters": {
        "name": "main"
      }
    }
  ],
  "edges": [
    {
      "source": "Stage[main]",
      "target": "Class[Settings]"
    },
    {
      "source": "Stage[main]",
      "target": "Class[main]"
    }
  ],
  "classes": [
    "settings"
  ]
}
```

Which aligns with what is provided by mgmtgraph, however that does *not* contain the expected resources.

Performing a `sudo /opt/puppetlabs/bin/puppet catalog download` however produced the following:
```
Warning: Setting configtimeout is deprecated. 
   (location: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:1163:in `issue_deprecation_warning')
Notice: Saved catalog for srv-2.ncs.net to /var/lib/puppet/client_yaml/catalog/srv-2.ncs.net.yaml
```
and the first few lines of this look a bit more promising:
```
--- !ruby/object:Puppet::Resource::Catalog
tags:
- settings
- ncs::sensu
- ncs
- sensu
- ncs::sensu::services
- services
- ncs::net
- net
- locales::params
- locales
- params
- ncs::ntp
- ntp
- ntp::params
- ca_cert::params
- ca_cert
```
